# Generated by Django 2.0 on 2018-06-17 03:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180617_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Invalid Phone Number.', regex='^[0-9]{10}$'), django.core.validators.MinLengthValidator(10)]),
        ),
    ]
